### ISSUE TITLE
Home page jumbotron is not properly positioned

### ISSUE THREAD

**Issue by polinakrusteva** [miroslavLalev/elearning#2]
Home page jumbotron is stick to the top when it should be in the middle, justified to other page elements. :scream: Please fix ASAP.
![screenshot 342](https://cloud.githubusercontent.com/assets/11165601/26753965/26ae6132-487a-11e7-8eb3-3ed0640342ec.png)

**Comment by miroslavLalev** [comment]
I removed the top:15% with the thoughts to fix it. Shall be done soon.

**Comment by miroslavLalev** [comment]
I have done a change that corrects the jumbotron position. Please review #3 so I can merge it.
